name: Build and deploy Django + React to Azure Web App - TorusPuzzle

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repo
      - name: Checkout repo
        uses: actions/checkout@v4

      # 2. Setup Node.js (for React)
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      # 3. Setup Python (only needed for local React build & Django management commands)
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # 4. Build React frontend
      - name: Build React frontend
        working-directory: ./frontend
        env:
          NPM_CONFIG_LEGACY_PEER_DEPS: 'true'
        run: |
          npm install ajv@6 ajv-keywords@3 --save-dev
          npm ci
          npm run build
          mkdir -p ../Qbackend/templates ../Qbackend/static
          cp -r build/* ../Qbackend/templates/
          cp -r build/static/* ../Qbackend/static/

      # 5. Django migrate & collectstatic locally (optional)
      # This ensures static files are ready in the zip
      - name: Django migrate & collectstatic
        env:
          DJANGO_SETTINGS_MODULE: Qbackend.settings
        run: |
          python Qbackend/manage.py migrate --noinput
          python Qbackend/manage.py collectstatic --noinput

      # 6. Archive everything (source + requirements + static files)
      - name: Archive app
        run: |
          zip -r app.zip Qbackend frontend requirements.txt

      # 7. Login to Azure
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}

      # 8. Deploy to Azure Web App
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'TorusPuzzle'
          slot-name: 'Production'
          package: app.zip
