- uses: actions/setup-python@v4
  with:
    python-version: '3.11'

- name: Install dependencies
  run: |
    pip install -r requirements.txt

- name: Azure WebApp Deploy
  uses: azure/webapps-deploy@v2
  with:
    app-name: <YOUR_APP_NAME>
    slot-name: 'production'
    publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
