name: Deploy Django + React to Azure

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    # 1. Build React frontend
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Install frontend deps
      run: |
        cd frontend
        npm install --legacy-peer-deps
        npm run build

    # 2. Setup Python
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install Python deps
      run: pip install -r requirements.txt

    # 3. Collect Django static files and migrate
    - name: Collect static and migrate
      run: |
        python Qbackend/manage.py collectstatic --noinput
        python Qbackend/manage.py migrate

    # 4. Deploy to Azure
    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: TorusPuzzle
        slot-name: production
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: .
